---@meta

---@class ABP_HDPlayerCharacterBase_C : AHDPlayerCharacter
---@field UberGraphFrame FPointerToUberGraphFrame
---@field LeanComponent USceneComponent
---@field HDAIPerception UHDAIPerceptionComponent
---@field TargetCameraPoint USceneComponent
---@field RefPoint USceneComponent
---@field NavigationInvoker UNavigationInvokerComponent
---@field Suppression_B UBoxComponent
---@field Suppression_A UBoxComponent
---@field Suppression_L UBoxComponent
---@field Suppression_R UBoxComponent
---@field VOIPTalker UBP_HDVOIPTalker_C
---@field PlayerNameTextRender UTextRenderComponent
---@field POI UDFPOIComponent
---@field CameraAnimationSlot2_CameraCurve_24954BCF4915EDB59EB9158824582DBB FVector
---@field CameraAnimationSlot2__Direction_24954BCF4915EDB59EB9158824582DBB ETimelineDirection::Type
---@field CameraAnimationSlot2 UTimelineComponent
---@field CameraAnimationSlot1_CameraCurve_78B6BF4045FC86DC6E1F7DACE85CA8B3 FVector
---@field CameraAnimationSlot1__Direction_78B6BF4045FC86DC6E1F7DACE85CA8B3 ETimelineDirection::Type
---@field CameraAnimationSlot1 UTimelineComponent
---@field CameraAnimationSlot0_CameraCurve_FCA6C1774AD24955E6AD27B43792174B FVector
---@field CameraAnimationSlot0__Direction_FCA6C1774AD24955E6AD27B43792174B ETimelineDirection::Type
---@field CameraAnimationSlot0 UTimelineComponent
---@field CrouchExitSpringArmTranslation_CameraVector_E70B91E543398207A70C939B80788F86 FVector
---@field CrouchExitSpringArmTranslation__Direction_E70B91E543398207A70C939B80788F86 ETimelineDirection::Type
---@field CrouchExitSpringArmTranslation UTimelineComponent
---@field CrouchSpringArmTranslation_CameraCurve_C4C40FDD4BBC021213AF31AA7F3DBF4B FVector
---@field CrouchSpringArmTranslation__Direction_C4C40FDD4BBC021213AF31AA7F3DBF4B ETimelineDirection::Type
---@field CrouchSpringArmTranslation UTimelineComponent
---@field ProneExitSpringArmTranslation_CurveVector_CEF9B5C9468424E977B84F9F84E59E08 FVector
---@field ProneExitSpringArmTranslation__Direction_CEF9B5C9468424E977B84F9F84E59E08 ETimelineDirection::Type
---@field ProneExitSpringArmTranslation UTimelineComponent
---@field ProneSpringArmTranslation_CurveVector_B542793B44FD44A9C91CC7B34C17770E FVector
---@field ProneSpringArmTranslation__Direction_B542793B44FD44A9C91CC7B34C17770E ETimelineDirection::Type
---@field ProneSpringArmTranslation UTimelineComponent
---@field VaultCameraTimeline_Rotation_22F2E311466556389CC02182AEE99CCA FVector
---@field VaultCameraTimeline_VaultCamera_22F2E311466556389CC02182AEE99CCA FVector
---@field VaultCameraTimeline__Direction_22F2E311466556389CC02182AEE99CCA ETimelineDirection::Type
---@field VaultCameraTimeline UTimelineComponent
---@field LerpTimeline_Lerp_5E919E724A951192A68B8180576AB695 float
---@field LerpTimeline__Direction_5E919E724A951192A68B8180576AB695 ETimelineDirection::Type
---@field LerpTimeline UTimelineComponent
---@field DamageEffectTimeline_DamageEffect_BEBC6E9841C4A26EF0A22DA008BD6CA4 FVector
---@field DamageEffectTimeline__Direction_BEBC6E9841C4A26EF0A22DA008BD6CA4 ETimelineDirection::Type
---@field DamageEffectTimeline UTimelineComponent
---@field SuppressionTimeline_SuppressionCurve_83869DB54889A3FECCAF0E83EA19C04B FVector
---@field SuppressionTimeline__Direction_83869DB54889A3FECCAF0E83EA19C04B ETimelineDirection::Type
---@field SuppressionTimeline UTimelineComponent
---@field FallDamageDivisor float
---@field FallDamageThreshold float
---@field EquipmentTimerDelay float
---@field bEquipmentKeyPressed boolean
---@field bSelectingEquipmentBySlot boolean
---@field bNextItem boolean
---@field LastValidPlayerState APlayerState
---@field bTintTeamColorForPlayerPOIs boolean
---@field bUseSpecialSymbolForLocalPlayerPOIs boolean
---@field LocalPlayerPOISymbol UTexture2D
---@field VOIPSpatializedAttenuation USoundAttenuation
---@field VOIPSpatializedSrcEffectChain USoundEffectSourcePresetChain
---@field HealthRegenTimer FTimerHandle
---@field bHealthRegenEnabled boolean
---@field HealthRegenAmount float
---@field HealthRegenTimerInterval float
---@field LocalPlayerPOITint FLinearColor
---@field RedTeamColor FColor
---@field BlueTeamColor FColor
---@field NoTeamColor FColor
---@field bRadialMenuEnabled boolean
---@field RadialMenu UWBP_HDRadialMenu_C
---@field RadialMenuExitSnd USoundBase
---@field RadialMenuOptions UDataTable
---@field bRallypointsEnabled boolean
---@field RadialMenuRallypointTimeDeployed float
---@field bSpatializedVOIPTalker boolean
---@field bOutpostsEnabled boolean
---@field RadialMenuOutpostTimeDeployed float
---@field SuppressionSound USoundBase
---@field SuppressionSoundVolume float
---@field bBracedAim boolean
---@field bWantsMount boolean
---@field bMounted boolean
---@field MountDirection FVector
---@field MountPosition FVector
---@field MountTransform FTransform
---@field SmoothSightDirection FVector
---@field SmoothSightOffset FVector
---@field AimSpeed float
---@field SightDirectionSmoothingSpeed float
---@field SightPositionSmoothingSpeed float
---@field MountDistance float
---@field AimAlpha float
---@field MountHeight float
---@field EquippedWeapon ABP_HDWeaponBase_C
---@field SpawnedFOB ABP_HDProj_SPDeployableBase_C
---@field SpawnedRallypoint ABP_HDProj_SPDeployableBase_C
---@field OnSuppression FBP_HDPlayerCharacterBase_COnSuppression
---@field OnHitDamage FBP_HDPlayerCharacterBase_COnHitDamage
---@field bSpottingEnabled boolean
---@field SuppressionCurve UCurveVector
---@field HitDamageCurve UCurveVector
---@field SuppressionCameraShake TSubclassOf<UCameraShake>
---@field ReceiveDamageCameraShake TSubclassOf<UCameraShake>
---@field HitEffectValues FLinearColor
---@field BleedingEffectValues FLinearColor
---@field DamageEffectStartPercent float
---@field bVariationDataSet boolean
---@field MinVaultViewYaw float
---@field MaxVaultViewYaw float
---@field VaultOverCameraCurve UCurveVector
---@field SprintVaultOverCameraCurve UCurveVector
---@field ClimbOntoCameraCurve UCurveVector
---@field SprintClimbOntoCameraCurve UCurveVector
---@field Camera1POffsetBeforeVault FVector
---@field Mesh1POffsetBeforeVault FVector
---@field SuppresionEffect FWeightedBlendable
---@field DamageEffect FWeightedBlendable
---@field ThirdPersonCharMatArray TArray<UMaterialInstanceDynamic>
---@field FirstPersonCharMatArray TArray<UMaterialInstanceDynamic>
---@field bUseSpecialSymbolForSquadMatePOIs boolean
---@field SquadMatePOISymbol UTexture2D
---@field SquadMatePOITint FLinearColor
---@field NonSquadMatePOISymbol UTexture2D
---@field NonSquadMatePOITint FLinearColor
---@field bUseSpecialSymbolForSquadLeaderPOIs boolean
---@field SquadLeaderPOISymbol UTexture2D
---@field SquadLeaderPOITint FLinearColor
---@field SquadLeaderPOITextColor FLinearColor
---@field NonSquadLeaderPOISymbol UTexture2D
---@field NonSquadLeaderPOITint FLinearColor
---@field NonSquadLeaderPOITextColor FLinearColor
---@field BracedAimAlpha float
---@field CameraCurveVectorTimeline UTimelineComponent
---@field bReloadPressed boolean
---@field ReloadAlpha float
---@field UnequipAlpha float
---@field LeanCompRotation FRotator
---@field LeanMovementAlpha float
---@field IsInAir boolean
---@field LeanAlpha float
---@field CrouchAlpha float
---@field SpringArmLocationCache FVector
---@field CameraAnimationScale float
---@field FiringAlpha float
---@field CrawlingAlpha float
---@field bCrouchState boolean
---@field bProneState boolean
---@field bProneInProgress boolean
---@field bTransitionInProgress boolean
---@field EyeHeightAdjust float
---@field MoveInputAxis float
---@field bPlayCameraAnimation_0 boolean
---@field CameraAnimationAlpha_0 float
---@field CameraAnimationCurve_0 UCurveVector
---@field CameraAnimationTransform_0 FTransform
---@field CameraAnimationSmoothingSpeed_0 float
---@field CameraAnimationTransitionSpeed_0 float
---@field bPlayCameraAnimation_1 boolean
---@field CameraAnimationAlpha_1 float
---@field CameraAnimationCurve_1 UCurveVector
---@field CameraAnimationTransform_1 FTransform
---@field CameraAnimationSmoothingSpeed_1 float
---@field CameraAnimationTransitionSpeed_1 float
---@field bPlayCameraAnimation_2 boolean
---@field CameraAnimationAlpha_2 float
---@field CameraAnimationCurve_2 UCurveVector
---@field CameraAnimationTransform_2 FTransform
---@field CameraAnimationSmoothingSpeed_2 float
---@field CameraAnimationTransitionSpeed_2 float
---@field bHoldForwardTrack0 boolean
---@field bHoldForwardTrack1 boolean
---@field bHoldForwardTrack2 boolean
---@field bTrackReset0 boolean
---@field bTrackReset1 boolean
---@field bTrackReset2 boolean
---@field bFireModeChanged boolean
ABP_HDPlayerCharacterBase_C = {}

---@return FVector
function ABP_HDPlayerCharacterBase_C:EventGetFocalPoint() end
function ABP_HDPlayerCharacterBase_C:WeaponCollision() end
function ABP_HDPlayerCharacterBase_C:LeanRotation() end
---@param EyeHeightAdjust float
function ABP_HDPlayerCharacterBase_C:GetEyeHeightAdjustment(EyeHeightAdjust) end
---@param CurveZ float
function ABP_HDPlayerCharacterBase_C:SetSpringArmOffset(CurveZ) end
---@param LocalController ABP_HDPlayerControllerBase_C
---@param bSameSquad boolean
function ABP_HDPlayerCharacterBase_C:IsSameSquad(LocalController, bSameSquad) end
---@param VaultBehavior EVaultBehavior
---@param CameraCurve UCurveVector
function ABP_HDPlayerCharacterBase_C:GetVaultCameraCurveForBehavior(VaultBehavior, CameraCurve) end
function ABP_HDPlayerCharacterBase_C:RestorePCViewRotationYawLimits() end
---@param ViewYawMin float
---@param ViewYawMax float
---@param bRelativeToActorRotation boolean
function ABP_HDPlayerCharacterBase_C:SetPCViewRotationYawLimits(ViewYawMin, ViewYawMax, bRelativeToActorRotation) end
---@param NewMesh USkeletalMesh
---@param bUpdateFPPMesh boolean
function ABP_HDPlayerCharacterBase_C:UpdateCharMesh(NewMesh, bUpdateFPPMesh) end
---@param PrimComp UPrimitiveComponent
---@param bNewActive boolean
function ABP_HDPlayerCharacterBase_C:SetSuppressionCompIsActive(PrimComp, bNewActive) end
---@param bActive boolean
function ABP_HDPlayerCharacterBase_C:SetSuppressionActive(bActive) end
---@param bAreEnemiesNearby boolean
function ABP_HDPlayerCharacterBase_C:CalcOutpostEnemiesNearbyRestriction(bAreEnemiesNearby) end
---@param bAreEnemiesNearby boolean
function ABP_HDPlayerCharacterBase_C:CalcRallypointEnemiesNearbyRestriction(bAreEnemiesNearby) end
---@param bNumberLimitReached boolean
function ABP_HDPlayerCharacterBase_C:IsOutpostNumberLimitReached(bNumberLimitReached) end
---@param bNumberLimitReached boolean
function ABP_HDPlayerCharacterBase_C:IsRallypointNumberLimitReached(bNumberLimitReached) end
---@param bIsOutpostDistanceRestricted boolean
function ABP_HDPlayerCharacterBase_C:CalcOutpostDistanceRestriction(bIsOutpostDistanceRestricted) end
---@param bIsRallypointDistanceRestricted boolean
function ABP_HDPlayerCharacterBase_C:CalcRallypointDistanceRestriction(bIsRallypointDistanceRestricted) end
---@param bIsSpawnedRallypointValid boolean
function ABP_HDPlayerCharacterBase_C:GetIsSpawnedRallypointValid(bIsSpawnedRallypointValid) end
---@param bIsSpawnedOutpostValid boolean
function ABP_HDPlayerCharacterBase_C:GetIsSpawnedOutpostValid(bIsSpawnedOutpostValid) end
---@param BoxSize FVector
---@param Distance float
---@param MaxHeight float
---@param MinHeight float
---@param MinSpace float
---@param bCouldMount boolean
---@param MountPosition FVector
function ABP_HDPlayerCharacterBase_C:GetProneMountPosition(BoxSize, Distance, MaxHeight, MinHeight, MinSpace, bCouldMount, MountPosition) end
---@param MinSightDistance float
function ABP_HDPlayerCharacterBase_C:AlignSights(MinSightDistance) end
---@param Direction FVector
---@param WallDistance float
---@param TraceRadius float
---@param CornerDistance float
---@param CapsuleHeight float
---@param bCouldMount boolean
---@param Position FVector
---@param Transform FTransform
function ABP_HDPlayerCharacterBase_C:GetMountPosition(Direction, WallDistance, TraceRadius, CornerDistance, CapsuleHeight, bCouldMount, Position, Transform) end
function ABP_HDPlayerCharacterBase_C:OnRep_bSpatializedVOIPTalker() end
---@param bRequireRallyPointAbility boolean
---@param bUsingSquadLeaderKit boolean
function ABP_HDPlayerCharacterBase_C:HasSquadLeaderKit(bRequireRallyPointAbility, bUsingSquadLeaderKit) end
---@param bSquadLeader boolean
function ABP_HDPlayerCharacterBase_C:IsSquadLeader(bSquadLeader) end
---@param SquadState AHDSquadState
function ABP_HDPlayerCharacterBase_C:GetSquadState(SquadState) end
---@param bSelectable boolean
function ABP_HDPlayerCharacterBase_C:CanSelectAnyRadialMenuOption(bSelectable) end
---@param bSelectable boolean
function ABP_HDPlayerCharacterBase_C:RadialMenuCanSelectOutpost(bSelectable) end
---@param bSelectable boolean
function ABP_HDPlayerCharacterBase_C:RadialMenuCanSelectRallypoint(bSelectable) end
---@param bSelectable boolean
function ABP_HDPlayerCharacterBase_C:RadialMenuCanSelectSpot(bSelectable) end
function ABP_HDPlayerCharacterBase_C:RadialMenuSelectOutpost() end
function ABP_HDPlayerCharacterBase_C:RadialMenuSelectRallypoint() end
function ABP_HDPlayerCharacterBase_C:RadialMenuSelectSpot() end
---@param Category FName
---@param SubItem FName
function ABP_HDPlayerCharacterBase_C:SelectRadialMenuItem(Category, SubItem) end
---@param SPDeployableClass TSubclassOf<ABP_HDProj_SPDeployableBase_C>
---@param SpawnOffset FVector
---@param SpawnedDeployableSP ABP_HDProj_SPDeployableBase_C
function ABP_HDPlayerCharacterBase_C:SpawnAndInitDeployableSPAtPawn(SPDeployableClass, SpawnOffset, SpawnedDeployableSP) end
function ABP_HDPlayerCharacterBase_C:LeanDebug() end
---@param LocalController AController
---@param bMatchingTeam boolean
function ABP_HDPlayerCharacterBase_C:IsMatchingTeam(LocalController, bMatchingTeam) end
---@param PlayerTeam EHDTeam
---@param FactionInfoClass TSubclassOf<UBP_HDFactionInfoBase_C>
function ABP_HDPlayerCharacterBase_C:GetPlayerFactionInfoClass(PlayerTeam, FactionInfoClass) end
function ABP_HDPlayerCharacterBase_C:ClearHealthRegenTimer() end
---@param NewHealth float
function ABP_HDPlayerCharacterBase_C:SetHealthRegenTimerIfInvalid(NewHealth) end
function ABP_HDPlayerCharacterBase_C:HealthRegenTimerElapsed() end
---@param bDestroyedComp boolean
function ABP_HDPlayerCharacterBase_C:CleanupVOIPTalker(bDestroyedComp) end
function ABP_HDPlayerCharacterBase_C:SetupVOIPTalker() end
---@param bSwitchFireModeForSelected boolean
function ABP_HDPlayerCharacterBase_C:EquipSelectedItemFromInventory(bSwitchFireModeForSelected) end
---@param PlayerLoadout UHDKit
function ABP_HDPlayerCharacterBase_C:GetMostValidLoadout(PlayerLoadout) end
---@param FactionInfoClass TSubclassOf<UDFFactionInfo>
function ABP_HDPlayerCharacterBase_C:GetMostValidTeamFactionInfo(FactionInfoClass) end
---@param TeamState ADFTeamState
function ABP_HDPlayerCharacterBase_C:GetMostValidTeamState(TeamState) end
---@param PlayerState APlayerState
function ABP_HDPlayerCharacterBase_C:GetMostValidPlayerState(PlayerState) end
---@return USkeletalMesh
function ABP_HDPlayerCharacterBase_C:ReceiveGetDefaultPawnMesh1P() end
function ABP_HDPlayerCharacterBase_C:UpdateEquipmentItems() end
function ABP_HDPlayerCharacterBase_C:UpdatePOIState() end
---@param Controller AController
---@param MinimapWidget UDFMinimap
function ABP_HDPlayerCharacterBase_C:GetMinimapWidget(Controller, MinimapWidget) end
---@param VariationHandle FDFCharacterVariationDataHandle
---@param bApplyToFPP boolean
function ABP_HDPlayerCharacterBase_C:ApplyCharacterVariation(VariationHandle, bApplyToFPP) end
---@param MeshFPP USkeletalMesh
---@param MeshTPP USkeletalMesh
function ABP_HDPlayerCharacterBase_C:UpdateCharMeshes(MeshFPP, MeshTPP) end
function ABP_HDPlayerCharacterBase_C:UpdateCharMeshesFromFaction() end
---@param EquipSlotNum int32
---@param bEquipImmediately boolean
---@param bFromInput boolean
function ABP_HDPlayerCharacterBase_C:SelectEquipmentBySlotNum(EquipSlotNum, bEquipImmediately, bFromInput) end
function ABP_HDPlayerCharacterBase_C:SetEquipmentTimer() end
function ABP_HDPlayerCharacterBase_C:StartEquipmentTimer() end
function ABP_HDPlayerCharacterBase_C:FreeAiming() end
function ABP_HDPlayerCharacterBase_C:UserConstructionScript() end
function ABP_HDPlayerCharacterBase_C:LerpTimeline__FinishedFunc() end
function ABP_HDPlayerCharacterBase_C:LerpTimeline__UpdateFunc() end
function ABP_HDPlayerCharacterBase_C:DamageEffectTimeline__FinishedFunc() end
function ABP_HDPlayerCharacterBase_C:DamageEffectTimeline__UpdateFunc() end
function ABP_HDPlayerCharacterBase_C:SuppressionTimeline__FinishedFunc() end
function ABP_HDPlayerCharacterBase_C:SuppressionTimeline__UpdateFunc() end
function ABP_HDPlayerCharacterBase_C:VaultCameraTimeline__FinishedFunc() end
function ABP_HDPlayerCharacterBase_C:VaultCameraTimeline__UpdateFunc() end
function ABP_HDPlayerCharacterBase_C:ProneSpringArmTranslation__FinishedFunc() end
function ABP_HDPlayerCharacterBase_C:ProneSpringArmTranslation__UpdateFunc() end
function ABP_HDPlayerCharacterBase_C:ProneExitSpringArmTranslation__FinishedFunc() end
function ABP_HDPlayerCharacterBase_C:ProneExitSpringArmTranslation__UpdateFunc() end
function ABP_HDPlayerCharacterBase_C:CrouchSpringArmTranslation__FinishedFunc() end
function ABP_HDPlayerCharacterBase_C:CrouchSpringArmTranslation__UpdateFunc() end
function ABP_HDPlayerCharacterBase_C:CrouchExitSpringArmTranslation__FinishedFunc() end
function ABP_HDPlayerCharacterBase_C:CrouchExitSpringArmTranslation__UpdateFunc() end
function ABP_HDPlayerCharacterBase_C:CameraAnimationSlot2__FinishedFunc() end
function ABP_HDPlayerCharacterBase_C:CameraAnimationSlot2__UpdateFunc() end
function ABP_HDPlayerCharacterBase_C:CameraAnimationSlot1__FinishedFunc() end
function ABP_HDPlayerCharacterBase_C:CameraAnimationSlot1__UpdateFunc() end
function ABP_HDPlayerCharacterBase_C:CameraAnimationSlot0__FinishedFunc() end
function ABP_HDPlayerCharacterBase_C:CameraAnimationSlot0__UpdateFunc() end
---@param Key FKey
function ABP_HDPlayerCharacterBase_C:InpActEvt_NextItem_K2Node_InputActionEvent_16(Key) end
---@param Key FKey
function ABP_HDPlayerCharacterBase_C:InpActEvt_PreviousItem_K2Node_InputActionEvent_15(Key) end
---@param Key FKey
function ABP_HDPlayerCharacterBase_C:InpActEvt_CameraToggle_K2Node_InputActionEvent_14(Key) end
---@param Key FKey
function ABP_HDPlayerCharacterBase_C:InpActEvt_EqpSlot0_K2Node_InputActionEvent_13(Key) end
---@param Key FKey
function ABP_HDPlayerCharacterBase_C:InpActEvt_EqpSlot1_K2Node_InputActionEvent_12(Key) end
---@param Key FKey
function ABP_HDPlayerCharacterBase_C:InpActEvt_EqpSlot2_K2Node_InputActionEvent_11(Key) end
---@param Key FKey
function ABP_HDPlayerCharacterBase_C:InpActEvt_EqpSlot3_K2Node_InputActionEvent_10(Key) end
---@param Key FKey
function ABP_HDPlayerCharacterBase_C:InpActEvt_EqpSlot4_K2Node_InputActionEvent_9(Key) end
---@param Key FKey
function ABP_HDPlayerCharacterBase_C:InpActEvt_EqpSlot5_K2Node_InputActionEvent_8(Key) end
---@param Key FKey
function ABP_HDPlayerCharacterBase_C:InpActEvt_EqpSlot6_K2Node_InputActionEvent_7(Key) end
---@param Key FKey
function ABP_HDPlayerCharacterBase_C:InpActEvt_EqpSlot7_K2Node_InputActionEvent_6(Key) end
---@param Key FKey
function ABP_HDPlayerCharacterBase_C:InpActEvt_EqpSlot8_K2Node_InputActionEvent_5(Key) end
---@param Key FKey
function ABP_HDPlayerCharacterBase_C:InpActEvt_EqpSlot9_K2Node_InputActionEvent_4(Key) end
---@param Key FKey
function ABP_HDPlayerCharacterBase_C:InpActEvt_CycleWeaponSights_K2Node_InputActionEvent_3(Key) end
---@param Key FKey
function ABP_HDPlayerCharacterBase_C:InpActEvt_PointAimToggle_K2Node_InputActionEvent_2(Key) end
---@param Key FKey
function ABP_HDPlayerCharacterBase_C:InpActEvt_RadialMenu_K2Node_InputActionEvent_1(Key) end
---@param Key FKey
function ABP_HDPlayerCharacterBase_C:InpActEvt_RadialMenu_K2Node_InputActionEvent_0(Key) end
---@param DeltaSeconds float
function ABP_HDPlayerCharacterBase_C:ReceiveTick(DeltaSeconds) end
---@param KillingDamage float
---@param DamageEvent FDamageEvent
---@param InstigatingPawn APawn
---@param DamageCauser AActor
function ABP_HDPlayerCharacterBase_C:OnDeath(KillingDamage, DamageEvent, InstigatingPawn, DamageCauser) end
function ABP_HDPlayerCharacterBase_C:OnEquipmentTimerElapsed() end
function ABP_HDPlayerCharacterBase_C:ReceiveCurrentLoadout() end
function ABP_HDPlayerCharacterBase_C:RetryLoadout() end
---@param NewController AController
function ABP_HDPlayerCharacterBase_C:ReceivePossessed(NewController) end
function ABP_HDPlayerCharacterBase_C:OnPCFirePressed() end
---@param Hit FHitResult
function ABP_HDPlayerCharacterBase_C:OnLanded(Hit) end
function ABP_HDPlayerCharacterBase_C:GenericDamageFeedback() end
function ABP_HDPlayerCharacterBase_C:ReceiveRestart() end
function ABP_HDPlayerCharacterBase_C:ReceiveDestroyed() end
---@param LastTeamNum uint8
---@param NewTeamNum uint8
function ABP_HDPlayerCharacterBase_C:ReceivePawnTeamNumUpdated(LastTeamNum, NewTeamNum) end
---@param DeltaSeconds float
function ABP_HDPlayerCharacterBase_C:ReceiveFreeAim(DeltaSeconds) end
---@param NewPlayerState APlayerState
---@param OldPlayerState APlayerState
function ABP_HDPlayerCharacterBase_C:NotifyPlayerStateChanged(NewPlayerState, OldPlayerState) end
function ABP_HDPlayerCharacterBase_C:ReceiveBeginPlay() end
---@param bFirstPerson boolean
function ABP_HDPlayerCharacterBase_C:FirstPersonToggled(bFirstPerson) end
function ABP_HDPlayerCharacterBase_C:OnPCFireReleased() end
---@param PS APlayerState
---@param NewPlayerName FString
function ABP_HDPlayerCharacterBase_C:PlayerNameChanged(PS, NewPlayerName) end
---@param EndPlayReason EEndPlayReason::Type
function ABP_HDPlayerCharacterBase_C:ReceiveEndPlay(EndPlayReason) end
---@param OldController AController
function ABP_HDPlayerCharacterBase_C:ReceiveUnpossessed(OldController) end
---@param Damage float
---@param DamageType UDamageType
---@param InstigatedBy AController
---@param DamageCauser AActor
function ABP_HDPlayerCharacterBase_C:ReceiveAnyDamage(Damage, DamageType, InstigatedBy, DamageCauser) end
function ABP_HDPlayerCharacterBase_C:EventResetHealthEffect() end
---@param TeamStateBeforeUpdate ADFTeamState
---@param NewTeamState ADFTeamState
---@param bNewTeamStateInit boolean
function ABP_HDPlayerCharacterBase_C:ReceivePawnTeamStateUpdated(TeamStateBeforeUpdate, NewTeamState, bNewTeamStateInit) end
---@param PrevMovementMode EMovementMode
---@param NewMovementMode EMovementMode
---@param PrevCustomMode uint8
---@param NewCustomMode uint8
function ABP_HDPlayerCharacterBase_C:K2_OnMovementModeChanged(PrevMovementMode, NewMovementMode, PrevCustomMode, NewCustomMode) end
---@param MsgTalkerChannel UDFCommChannel
---@param MsgTalkerPS APlayerState
---@param bMsgIsTalking boolean
function ABP_HDPlayerCharacterBase_C:ReceiveVoipTalkerMsgReceived(MsgTalkerChannel, MsgTalkerPS, bMsgIsTalking) end
function ABP_HDPlayerCharacterBase_C:ReceiveOnStartAim() end
function ABP_HDPlayerCharacterBase_C:ReceiveOnEndAim() end
---@param OverlappedComponent UPrimitiveComponent
---@param OtherActor AActor
---@param OtherComp UPrimitiveComponent
---@param OtherBodyIndex int32
---@param bFromSweep boolean
---@param SweepResult FHitResult
function ABP_HDPlayerCharacterBase_C:BndEvt__Suppression_B_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature(OverlappedComponent, OtherActor, OtherComp, OtherBodyIndex, bFromSweep, SweepResult) end
---@param OverlappedComponent UPrimitiveComponent
---@param OtherActor AActor
---@param OtherComp UPrimitiveComponent
---@param OtherBodyIndex int32
---@param bFromSweep boolean
---@param SweepResult FHitResult
function ABP_HDPlayerCharacterBase_C:BndEvt__Suppression_A_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature(OverlappedComponent, OtherActor, OtherComp, OtherBodyIndex, bFromSweep, SweepResult) end
---@param OverlappedComponent UPrimitiveComponent
---@param OtherActor AActor
---@param OtherComp UPrimitiveComponent
---@param OtherBodyIndex int32
---@param bFromSweep boolean
---@param SweepResult FHitResult
function ABP_HDPlayerCharacterBase_C:BndEvt__Suppression_L_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature(OverlappedComponent, OtherActor, OtherComp, OtherBodyIndex, bFromSweep, SweepResult) end
---@param OverlappedComponent UPrimitiveComponent
---@param OtherActor AActor
---@param OtherComp UPrimitiveComponent
---@param OtherBodyIndex int32
---@param bFromSweep boolean
---@param SweepResult FHitResult
function ABP_HDPlayerCharacterBase_C:BndEvt__Suppression_R_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(OverlappedComponent, OtherActor, OtherComp, OtherBodyIndex, bFromSweep, SweepResult) end
---@param OtherProjectile ADFBaseProjectile
---@param Pickup ADFBasePickup
---@param SuppressionVolume UPrimitiveComponent
function ABP_HDPlayerCharacterBase_C:SuppressionEffect(OtherProjectile, Pickup, SuppressionVolume) end
---@param NewEquippedItem ADFBaseItem
---@param PrevEquippedItem ADFBaseItem
function ABP_HDPlayerCharacterBase_C:ReceiveEquippedItemChanged(NewEquippedItem, PrevEquippedItem) end
---@param OtherProjectile ADFBaseProjectile
---@param Pickup ADFBasePickup
ABP_HDPlayerCharacterBase_C['Hit Damage'] = function(OtherProjectile, Pickup) end
function ABP_HDPlayerCharacterBase_C:ServerRadialMenuSelectOutpost() end
function ABP_HDPlayerCharacterBase_C:ServerRadialMenuSelectRallypoint() end
function ABP_HDPlayerCharacterBase_C:ServerRadialMenuSelectSpot() end
---@param DamageTaken float
---@param DamageEvent FDamageEvent
---@param PawnInstigator APawn
---@param DamageCauser AActor
---@param bKilled boolean
function ABP_HDPlayerCharacterBase_C:ReceivePlayHit(DamageTaken, DamageEvent, PawnInstigator, DamageCauser, bKilled) end
---@param NewVariation FDFCharacterVariationData
---@param PreviousVariation FDFCharacterVariationData
function ABP_HDPlayerCharacterBase_C:ReceiveVariationDataChanged(NewVariation, PreviousVariation) end
---@param NewHealthTotal float
---@param PrevHealthTotal float
function ABP_HDPlayerCharacterBase_C:ReceiveHealthChanged(NewHealthTotal, PrevHealthTotal) end
function ABP_HDPlayerCharacterBase_C:ReceiveOnStartVault() end
function ABP_HDPlayerCharacterBase_C:ReceiveOnEndVault() end
---@param HalfHeightAdjust float
---@param ScaledHalfHeightAdjust float
function ABP_HDPlayerCharacterBase_C:ReceiveOnStartProne(HalfHeightAdjust, ScaledHalfHeightAdjust) end
---@param HalfHeightAdjust float
---@param ScaledHalfHeightAdjust float
function ABP_HDPlayerCharacterBase_C:ReceiveOnEndProne(HalfHeightAdjust, ScaledHalfHeightAdjust) end
---@param HalfHeightAdjust float
---@param ScaledHalfHeightAdjust float
function ABP_HDPlayerCharacterBase_C:K2_OnStartCrouch(HalfHeightAdjust, ScaledHalfHeightAdjust) end
---@param HalfHeightAdjust float
---@param ScaledHalfHeightAdjust float
function ABP_HDPlayerCharacterBase_C:K2_OnEndCrouch(HalfHeightAdjust, ScaledHalfHeightAdjust) end
function ABP_HDPlayerCharacterBase_C:EnterRadialMenu() end
function ABP_HDPlayerCharacterBase_C:ExitRadialMenu() end
---@param Category FName
---@param SubItem FName
function ABP_HDPlayerCharacterBase_C:SubmenuCommited(Category, SubItem) end
---@param EntryPoint int32
function ABP_HDPlayerCharacterBase_C:ExecuteUbergraph_BP_HDPlayerCharacterBase(EntryPoint) end
---@param OtherProjectile ADFBaseProjectile
---@param Pickup ADFBasePickup
function ABP_HDPlayerCharacterBase_C:OnHitDamage__DelegateSignature(OtherProjectile, Pickup) end
---@param OtherProjectile ADFBaseProjectile
---@param Pickup ADFBasePickup
function ABP_HDPlayerCharacterBase_C:OnSuppression__DelegateSignature(OtherProjectile, Pickup) end


